export default [
    {
        "Rank": 1,
        "Title": "Sgt. Pepper's Lonely Hearts Club Band",
        "Band": "The Beatles",
        "Year": 1967,
        "Rating": 5,
        "Genre": "Rock",
    },
    {
        "Rank": 2,
        "Title": "Pet Sounds",
        "Band": "The Beach Boys",
        "Year": 1966,
        "Rating": 3,
        "Genre": "Undef.",
        
    },
    {
        "Rank": 3,
        "Title": "Revolver",
        "Band": "The Beatles",
        "Year": 1966,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 4,
        "Title": "Highway 61 Revisited",
        "Band": "Bob Dylan",
        "Year": 1965,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 5,
        "Title": "Rubber Soul",
        "Band": "The Beatles",
        "Year": 1965,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 6,
        "Title": "What's Going On",
        "Band": "Marvin Gaye",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 7,
        "Title": "Exile On Main St.",
        "Band": "The Rolling Stones",
        "Year": 1972,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 8,
        "Title": "London Calling",
        "Band": "The Clash",
        "Year": 1979,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 9,
        "Title": "Blonde On Blonde",
        "Band": "Bob Dylan",
        "Year": 1966,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 10,
        "Title": "The Beatles (The White Album)",
        "Band": "The Beatles",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 11,
        "Title": "The Sun Sessions",
        "Band": "Elvis Presley",
        "Year": 1976,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 12,
        "Title": "Kind Of Blue",
        "Band": "Miles Davis",
        "Year": 1959,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 13,
        "Title": "The Velvet Underground And Nico",
        "Band": "The Velvet Underground",
        "Year": 1967,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 14,
        "Title": "Abbey Road",
        "Band": "The Beatles",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 15,
        "Title": "Are You Experienced",
        "Band": "The Jimi Hendrix Experience",
        "Year": 1967,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 16,
        "Title": "Blood On The Tracks",
        "Band": "Bob Dylan",
        "Year": 1975,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 17,
        "Title": "Nevermind",
        "Band": "Nirvana",
        "Year": 1991,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 18,
        "Title": "Born To Run",
        "Band": "Bruce Springsteen",
        "Year": 1975,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 19,
        "Title": "Astral Weeks",
        "Band": "Van Morrison",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 20,
        "Title": "Thriller",
        "Band": "Michael Jackson",
        "Year": 1982,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 21,
        "Title": "The Great Twenty-Eight",
        "Band": "Chuck Berry",
        "Year": 1982,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 22,
        "Title": "John Lennon/Plastic Ono Band",
        "Band": "John Lennon",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 23,
        "Title": "Innervisions",
        "Band": "Stevie Wonder",
        "Year": 1973,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 24,
        "Title": "Live At The Apollo",
        "Band": "James Brown",
        "Year": 1963,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 25,
        "Title": "Rumours",
        "Band": "Fleetwood Mac",
        "Year": 1977,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 26,
        "Title": "The Joshua Tree",
        "Band": "U2",
        "Year": 1987,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 27,
        "Title": "King Of The Delta Blues Singers",
        "Band": "Robert Johnson",
        "Year": 1961,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 28,
        "Title": "Who's Next",
        "Band": "The Who",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 29,
        "Title": "Led Zeppelin",
        "Band": "Led Zeppelin",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 30,
        "Title": "Blue",
        "Band": "Joni Mitchell",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 31,
        "Title": "Bringing It All Back Home",
        "Band": "Bob Dylan",
        "Year": 1965,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 32,
        "Title": "Let It Bleed",
        "Band": "The Rolling Stones",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 33,
        "Title": "Ramones",
        "Band": "Ramones",
        "Year": 1976,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 34,
        "Title": "Music From Big Pink",
        "Band": "The Band",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 35,
        "Title": "The Rise And Fall Of Ziggy Stardust And The Spiders From Mars",
        "Band": "David Bowie",
        "Year": 1972,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 36,
        "Title": "Tapestry",
        "Band": "Carole King",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 37,
        "Title": "Hotel California",
        "Band": "Eagles",
        "Year": 1976,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 38,
        "Title": "The Anthology, 1947-1972",
        "Band": "Muddy Waters",
        "Year": 2001,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 39,
        "Title": "Please Please Me",
        "Band": "The Beatles",
        "Year": 1963,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 40,
        "Title": "Forever Changes",
        "Band": "Love",
        "Year": 1967,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 41,
        "Title": "Never Mind The Bollocks, Here's The Sex Pistols",
        "Band": "Sex Pistols",
        "Year": 1977,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 42,
        "Title": "The Doors",
        "Band": "The Doors",
        "Year": 1967,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 43,
        "Title": "The Dark Side Of The Moon",
        "Band": "Pink Floyd",
        "Year": 1973,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 44,
        "Title": "Horses",
        "Band": "Patti Smith",
        "Year": 1975,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 45,
        "Title": "The Band",
        "Band": "The Band",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 46,
        "Title": "Legend",
        "Band": "Bob Marley And The Wailers",
        "Year": 1984,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 47,
        "Title": "A Love Supreme",
        "Band": "John Coltrane",
        "Year": 1965,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 48,
        "Title": "It Takes A Nation Of Millions To Hold Us Back",
        "Band": "Public Enemy",
        "Year": 1988,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 49,
        "Title": "At Fillmore East",
        "Band": "The Allman Brothers Band",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 50,
        "Title": "Here's Little Richard",
        "Band": "Little Richard",
        "Year": 1957,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 51,
        "Title": "Bridge Over Troubled Water",
        "Band": "Simon And Garfunkel",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 52,
        "Title": "Greatest Hits",
        "Band": "Al Green",
        "Year": 1975,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 53,
        "Title": "The Birth of Soul: The Complete Atlantic Rhythm and Blues Recordings",
        "Band": "Ray Charles",
        "Year": 1991,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 54,
        "Title": "Electric Ladyland",
        "Band": "The Jimi Hendrix Experience",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 55,
        "Title": "Elvis Presley",
        "Band": "Elvis Presley",
        "Year": 1956,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 56,
        "Title": "Songs In The Key Of Life",
        "Band": "Stevie Wonder",
        "Year": 1976,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 57,
        "Title": "Beggars Banquet",
        "Band": "The Rolling Stones",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 58,
        "Title": "Trout Mask Replica",
        "Band": "Captain Beefheart And His Magic Band",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 59,
        "Title": "Meet The Beatles!",
        "Band": "The Beatles",
        "Year": 1964,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 60,
        "Title": "Greatest Hits",
        "Band": "Sly and the Family Stone",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 61,
        "Title": "Appetite For Destruction",
        "Band": "Guns N' Roses",
        "Year": 1987,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 62,
        "Title": "Achtung Baby",
        "Band": "U2",
        "Year": 1991,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 63,
        "Title": "Sticky Fingers",
        "Band": "The Rolling Stones",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 64,
        "Title": "Phil Spector, Back to Mono (1958 - 1969)",
        "Band": "Various Artists",
        "Year": 1991,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 65,
        "Title": "Moondance",
        "Band": "Van Morrison",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 66,
        "Title": "Led Zeppelin IV",
        "Band": "Led Zeppelin",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 67,
        "Title": "The Stranger",
        "Band": "Billy Joel",
        "Year": 1977,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 68,
        "Title": "Off The Wall",
        "Band": "Michael Jackson",
        "Year": 1979,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 69,
        "Title": "Superfly",
        "Band": "Curtis Mayfield",
        "Year": 1972,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 70,
        "Title": "Physical Graffiti",
        "Band": "Led Zeppelin",
        "Year": 1975,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 71,
        "Title": "After The Gold Rush",
        "Band": "Neil Young",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 72,
        "Title": "Purple Rain",
        "Band": "Prince & The Revolution",
        "Year": 1984,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 73,
        "Title": "Back In Black",
        "Band": "AC/DC",
        "Year": 1980,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 74,
        "Title": "Otis Blue / Otis Redding Sings Soul",
        "Band": "Otis Redding",
        "Year": 1965,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 75,
        "Title": "Led Zeppelin II",
        "Band": "Led Zeppelin",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 76,
        "Title": "Imagine",
        "Band": "John Lennon",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 77,
        "Title": "The Clash",
        "Band": "The Clash",
        "Year": 1977,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 78,
        "Title": "Harvest",
        "Band": "Neil Young",
        "Year": 1972,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 79,
        "Title": "Star Time",
        "Band": "James Brown",
        "Year": 1991,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 80,
        "Title": "Odessey And Oracle",
        "Band": "The Zombies",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 81,
        "Title": "Graceland",
        "Band": "Paul Simon",
        "Year": 1986,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 82,
        "Title": "Axis: Bold As Love",
        "Band": "The Jimi Hendrix Experience",
        "Year": 1967,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 83,
        "Title": "I Never Loved A Man The Way I Love You",
        "Band": "Aretha Franklin",
        "Year": 1967,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 84,
        "Title": "Lady Soul",
        "Band": "Aretha Franklin",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 85,
        "Title": "Born In The U.S.A.",
        "Band": "Bruce Springsteen",
        "Year": 1984,
        "Rating": 3,
        "Genre": "Undef."
    },
    {
        "Rank": 86,
        "Title": "Let It Be",
        "Band": "The Beatles",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 87,
        "Title": "The Wall",
        "Band": "Pink Floyd",
        "Year": 1979,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 88,
        "Title": "At Folsom Prison",
        "Band": "Johnny Cash",
        "Year": 1968,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 89,
        "Title": "Dusty in Memphis",
        "Band": "Dusty Springfield",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 90,
        "Title": "Talking Book",
        "Band": "Stevie Wonder",
        "Year": 1972,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 91,
        "Title": "Goodbye Yellow Brick Road",
        "Band": "Elton John",
        "Year": 1973,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 92,
        "Title": "20 Golden Greats",
        "Band": "Buddy Holly",
        "Year": 1978,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 93,
        "Title": "Sign 'O' The Times",
        "Band": "Prince",
        "Year": 1987,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 94,
        "Title": "Bitches Brew",
        "Band": "Miles Davis",
        "Year": 1970,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 95,
        "Title": "Green River",
        "Band": "Creedence Clearwater Revival",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 96,
        "Title": "Tommy",
        "Band": "The Who",
        "Year": 1969,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 97,
        "Title": "The Freewheelin' Bob Dylan",
        "Band": "Bob Dylan",
        "Year": 1963,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 98,
        "Title": "This Year's Model",
        "Band": "Elvis Costello",
        "Year": 1978,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 99,
        "Title": "There's A Riot Goin' On",
        "Band": "Sly and the Family Stone",
        "Year": 1971,
        "Rating": 3,
        "Genre": "Undef.",
    },
    {
        "Rank": 100,
        "Title": "In The Wee Small Hours",
        "Band": "Frank Sinatra",
        "Year": 1955,
        "Rating": 3,
        "Genre": "Undef.",
    }
];